### ISSUE TITLE
hard-coded installation path?

### ISSUE THREAD

**Issue by batpigandme** [nacnudus/smungs#1]
Hi Duncan,

Just got the following error message when trying to install this:
```
ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’
```

Obviously I'll go ahead and use `--no-staged-install`, but figured I'd do my duty by reporting it to the maintainer! Thanks for this!

**Comment by nacnudus** [comment]
Thanks Mara!

I'd forgotten this package existed, so I hope it doesn't cause you any other problems.
